#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright 2021 Google LLC
#
# Trigger the SCSI error handler.

. tests/scsi/rc
. common/scsi_debug

DESCRIPTION="Trigger the SCSI error handler"

QUICK=1

requires() {
	_have_scsi_debug
}

config_hz() {
	if [ -e /proc/config.gz ]; then
		zcat /proc/config.gz
	else
		cat "/boot/config-$(uname -r)"
	fi | sed -n 's/^CONFIG_HZ=//p'
}

set_scsi_debug_delay() {
	local freq jdelay
	local delay_s=$1

	freq=$(config_hz)
	jdelay=$((delay_s * freq))
	echo "CONFIG_HZ=${freq} jdelay=${jdelay}" >>"$FULL"
	echo "$jdelay" > /sys/module/scsi_debug/parameters/delay
}

# Convert X.YYYs time format into rounded up integer in seconds.
time_to_second() {
	local time_output=${1}

	time_output=${time_output/s/}
	time_output=${time_output%%.*}
	echo $((time_output + 1))
}

dd_read() {
	dd if="/dev/$dev" of=/dev/null bs=512 count=1 iflag=direct >&/dev/null
}

test() {
	local dev dd_time
	local delay_s ret
	local delay_margin_s=3

	echo "Running ${TEST_NAME}"

	if ! _init_scsi_debug delay=0; then
		return 1
	fi

	# Enable SCSI error handler logging
	echo 63 > /sys/module/scsi_mod/parameters/scsi_logging_level

	dev="${SCSI_DEBUG_DEVICES[0]}"
	# Change the block layer timeout to max(1 / CONFIG_HZ, 0.001)
	# seconds.
	echo 1 > "/sys/class/block/$dev/queue/io_timeout"
	echo "I/O timeout = $(<"/sys/class/block/$dev/queue/io_timeout")" >>"$FULL"

	# Change the scsi_debug delay to 3 seconds.
	delay_s=$delay_margin_s
	set_scsi_debug_delay $delay_s

	# Measure dd read time with error handling.
	dd_time=$( { time dd_read; } 2>&1 )
	ret=$?
	echo "dd with ${delay_s}s delay: ret=$ret time=$dd_time" >>"$FULL"
	dd_seconds=$(time_to_second "${dd_time}")

	# Adjust the scsi_debug delay to cover dd read time with error handling.
	delay_s=$((delay_margin_s + dd_seconds))
	set_scsi_debug_delay "$delay_s"

	# Confirm dd read fails after error handling.
	if dd_read; then
		echo "Reading from scsi_debug succeeded"
	else
		echo "Reading from scsi_debug failed"
	fi

	# Disable SCSI error handler logging
	echo 0 > /sys/module/scsi_mod/parameters/scsi_logging_level

	_exit_scsi_debug

	echo "Test complete"
}
